language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
      - android-sdk-license-.+
before_install:
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
script:
   - ./gradlew build